-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SumoApp.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import SumoApp.Scalar exposing (defaultCodecs)


type alias Date =
    SumoApp.Scalar.Date


codecs : SumoApp.Scalar.Codecs Date
codecs =
    SumoApp.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        }
