-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SumoApp.Subscription exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import SumoApp.InputObject
import SumoApp.Interface
import SumoApp.Object
import SumoApp.Scalar
import SumoApp.ScalarCodecs
import SumoApp.Union


wrestlerCreated :
    SelectionSet decodesTo SumoApp.Object.Wrestler
    -> SelectionSet (Maybe decodesTo) RootSubscription
wrestlerCreated object_ =
    Object.selectionForCompositeField "wrestlerCreated" [] object_ (identity >> Decode.nullable)
